development:
  adapter: postgresql
  encoding: unicode
  database: stock_tracker_development
  pool: 5
  username: khakob
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: stock_tracker_test
  pool: 5
  username: khakob
  password:
